# Site settings
title: Arthur Freitas
description: >-
  O Arthur é um desenvolvedor front-end e consultor WordPress que faz adoráveis sites à mão para pessoas bacanas.

url: "https://arthr.me"
baseurl: ""

lang: pt
locale: pt_BR
timezone: "America/Sao_Paulo"

author:
  name: Arthur Freitas
  url: "https://arthr.me"

# 🌱 settings
use_html_extension:  false
open_external_links_in_new_tab: true
embed_tweets: false

# Build settings
livereload: true
show_drafts: true
incremental: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

permalink: "/jardim/:title/"

exclude:
- _includes/posts_graph.json

# Plugin settings
plugins:
- jekyll-feed
- jekyll-json-feed
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-archives
- jekyll-loading-lazy
- jekyll-last-modified-at

# Plugin: jekyll-archives
jekyll-archives:
  enabled:
    - categories
    - tags
  permalinks:
    category: "/jardim/:name/"
    tag: "/jardim/tags/:name/"

# Plugin: jekyll-seo-tag
twitter:
  username: arthrfrts
  card: summary

social:
  name: Arthur Freitas
  links:
    - https://twitter.com/arthrfrts
    - https://github.com/arthrfrts
    - https://letterboxd.com/arthrfrts
    - https://www.last.fm/user/arthrfrts
    - https://www.flickr.com/photos/arthrfrts
