# Site settings

title: Arthur Freitas
email: email@arthr.me
description: >-
  O Arthur é um desenvolvedor web que faz sites adoráveis à mão.

lang: pt-BR
logo: "/assets/images/mii.png"

collections:
  projects:
    output: false
  games:
    output: true
    permalink: "/jogos/:title/"

# Build settings

# incremental: true

baseurl: ""
url: "https://arthr.me"

permalink: "/:title/"

keep_files:
  - assets/fonts
  - assets/images
  
exclude:
  - uploads
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  
# Plugin: jekyll-seo-tag

author:
  name: Arthur Freitas
  twitter: arthrfrts

twitter:
  username: arthrfrts
  card: summary
  
social:
  name: Arthur Freitas
  links:
    - https://twitter.com/arthrfrts
    - https://github.com/arthrfrts
    - https://www.linkedin.com/in/arthrfrts
    - https://letterboxd.com/arthrfrts
